// projects/sfx-web/src/pages/utils/timestamp.tsx
import React, { useEffect, useState } from 'react'

export default function TimestampPage () {
  const startUnix = Date.now()
  const [timeString, setTimeString] = useState<string>(new Date(startUnix).toUTCString())
  const [timestamp, setTimestamp] = useState<number>(Math.floor(startUnix / 1000))
  useEffect(() => {
    setInterval(() => {
      const nowUnix = Date.now()
      setTimestamp(Math.floor(nowUnix / 1000))
      setTimeString(new Date(nowUnix).toUTCString())
    }, 1000)
  }, [])

  return <div className={'timestamp-page'}>
    <div className={'content-body fx-card'}>
      <h2>
        现在的时间是
      </h2>
      <h3>
        {timeString}
      </h3>
      <h2>
        现在时间戳是
      </h2>
      <h3>
        {timestamp}
      </h3>
    </div>

  </div>
}

// projects/sfx-web/src/pages/utils/timestamp.svelte
<script lang="ts">
  import '@/components/card.svelte'

  const startUnix = Date.now()
  let timeString = new Date(startUnix).toUTCString()
  let timestamp = Math.floor(startUnix / 1000)

  setInterval(() => {
    const nowUnix = Date.now()
    timeString = new Date(nowUnix).toUTCString()
    timestamp = Math.floor(nowUnix / 1000)
  }, 1000)
</script>

<svelte:options tag="fx-timestamp"/>

<div class='timestamp-page'>
  <fx-card>
    <div class='content-body'>
      <h2>
        现在的时间是
      </h2>
      <h3>
        {timeString}
      </h3>
      <h2>
        现在时间戳是
      </h2>
      <h3>
        {timestamp}
      </h3>
    </div>
  </fx-card>
</div>

<style lang="scss">
  @import "src/styles/media";

  .timestamp-page {
    @media (min-width: $screen-desktop) {
      .content-body {
        width: 960px;
        margin: 0 auto;
      }
    }
  }
</style>
